name: Deploy NGINX to EC2 (Ubuntu)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: Install and start NGINX on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update -y
            sudo apt install nginx -y
            sudo systemctl enable nginx
            sudo systemctl start nginx
            sudo rm -rf /var/www/html/*
          EOF

      - name: Upload website files
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mv /tmp/index.html /var/www/html/index.html
          EOF
